### ISSUE TITLE
Rendering media

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Scripto#10]
We need to account for all types of media on the "Media review" page. The panzoom container works well for individual images, but is not appropriate for non-image media (e.g. MP3, MP4, OGG) or multi-page media (e.g. PDF, TIFF), even when a thumbnail has been created. We need strategies for rendering popular non-image/multi-page file formats that don't break the review layouts (horizontal, vertical, full screen).

Moreover, while the panzoom container works well for individual images, it could be better. Since we're rendering large thumbnails and not original files, the image quickly pixelates when zooming in. Short of tiling all original images and rendering through OpenSeadragon (a _huge_ dependency), our options are limited for high-resolution zoomable images. We could simply render original images in the panzoom container, but browsers will slow to a crawl for very large files. One solution is to place an arbitrary size limit on rendering original images and falling back to the thumbnail once it's exceeded.

**Comment by jimsafley** [comment]
About non-image/multi-page file formats: thankfully, modern browsers render audio and video gracefully when using `<audio>` and `<video>` tags, which Omeka automatically does. PDFs are still problematic, but we can direct users to install the [PDF Embed](https://github.com/zerocrates/PdfEmbedS) module. Multipage TIFFs are still problematic (Scripto renders the file as an individual image), but we could provide a direct link to the file somewhere on the page.

**Comment by zerocrates** [comment]
TIFFs generally will be problematic to do in decent quality as most browsers can't display the original no matter the size.

**Comment by jimsafley** [comment]
For now we're following this heuristic for using panzoom: the media must have an original file, the file size must be no more than 40MB, and the file must be an image that can be renderable in browsers. Otherwise we rely on Omeka's automatic media rendering, which I suspect is sufficient for most projects.

See `ScriptoMediaRepresentation::isRenderableImage()`
