### ISSUE TITLE
Admin: add approve/complete/protect controls to individual media review

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Scripto#2]
Reviewers need controls that fit within the flow of an individual media page that allow them to toggle a transcription as approved/not approved, completed/not completed, and protected/not protected. The approved and completed controls need extra space for approved/completed date and approved/completed by (i.e. user name).

**Comment by kimisgold** [comment]
Just did a pass for a simple always open sidebar containing these controls in https://github.com/omeka-s-modules/Scripto/commit/91364834540e079b343dc74fefd86d804b810a7a on the `review-media` branch.

**Comment by jimsafley** [comment]
Thanks. I like the always-open sidebar. I think power-reviewers will want wide buttons over checkboxes to toggle status. Also, we're currently not providing approval history.

**Comment by jimsafley** [comment]
After some consideration I do worry that the sidebar pushes the page contents over, therefore shrinking the rendered media, making it less suitable for review. This is particularly noticeable with media with wide aspect ratios. Perhaps reducing the size of the sidebar or an altogether different strategy?

**Comment by jimsafley** [comment]
Need to add a watch/unwatch control to the media review page too.

**Comment by jimsafley** [comment]
Ok, here's (what I hope will be) the final list of media review/manage actions that we should integrate into the "Review media" page:

**Review actions**
- Mark as approved / Mark as not approved
- Mark as completed / Mark as incomplete

**Manage actions**
- Add to your watchlist / Remove from your watchlist
- Restrict editing to admins / Restrict editing to logged in users / Open editing to all users

**Comment by jimsafley** [comment]
About the review/manage interface, here's a rough idea of what I had in mind:

![media review zmb zmb20001 jpg scripto whoameka 1](https://user-images.githubusercontent.com/141955/38056309-22ddd2f2-32aa-11e8-9804-e788dce26743.png)

For sure it can be streamlined and condensed into something less clunky, but this is more like what I've had in mind since first thinking about this project.

**Comment by mebrett** [comment]
@jimsafley I'd be happy to talk through this page with you and Kim (and also Alyssa), since I have experience in the process of reviewing. I have a few questions about how it works, if you have time next week to talk me through how it currently works.

**Comment by jimsafley** [comment]
@mebrett I recommend that you take a look at the current "Item review" page, in particular the "Batch manage actions" and "Batch edit protection actions" select options. Each of those actions will be available for individual media on the "Media review" page. Here's a general overview:

- **Mark as approved / Mark as not approved**: Marking media as "approved" is a formal indication that the media's transcription has been reviewed and deemed acceptable. Items where all child media have been approved are automatically considered approved. Scripto only imports transcriptions from approved media when importing.

- **Mark as completed / Mark as incomplete**: Marking media as "completed" is an informal indication that the media's transcription is finished and ready for review. Items where all child media have been completed are automatically considered completed. Media are typically marked as completed by transcribers once they feel no more work is needed.

- **Add to your watchlist / Remove from your watchlist**: MediaWiki provides all logged in users a personal watchlist where they can track selected pages for new modifications. It's helpful to keep track of pages related to your interest areas.

- **Allow all users / Allow only confirmed users / Allow only administrators**: MediaWiki provides administrators the ability to protect pages from editing depending on user level and expiry date. They can allow all users (includes anonymous users); allow only confirmed users (i.e. logged in users who meet a preset criteria); and allow only administrators (those with sysop credentials). They can also set a date when the protection expires. It's helpful to protect pages that are prone to vandalism and, perhaps, pages that are completed, approved, and not open to more work.
