### ISSUE TITLE
Public dashboard

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Scripto#22]
There's currently nothing on the public dashboard. I will be adding panels for "Recent contributions" and "Watchlist" for logged in users, but there's just a blank page for users who are not logged in. We need to consider the public dashboard's purpose and what information it needs to display, if any.

@kimisgold @mebrett Any ideas are welcome.

**Comment by kimisgold** [comment]
Here are some ideas for the overall purpose of the dashboard:

- A landing page for users to quickly access their recent work
- A "getting started" area for new users

I'm wondering if it'd be helpful to display media that has received no attention, like a list of task suggestions—I think this could be good default content for newly created accounts.

Speaking of new users, we could also plan some tutorial content for the new Scripto. This could be as simple as linked documentation.

**Comment by mebrett** [comment]
I like Kim's idea of task suggestions for new users (or anyone without recent work). 

Linking to the documentation would be good, and to any transcription guidelines the project sets up.

**Comment by mebrett** [comment]
The grant proposal includes at least one new screencast for the new Scripto, in addition to brand new documentation.
