### ISSUE TITLE
Scripto site block

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Scripto#23]
To round out the module, I need to add a way for site administrators to link their sites to Scripto projects. A simple "Scripto" page block containing a select menu of all projects should suffice. This will add a link directly to the project's item browse page. They can contextualize the link using surrounding blocks.

**Comment by jimsafley** [comment]
@mebrett @kimisgold I added a Scripto site block as described above. You can test it out by editing and viewing a site page. Is this sufficient? Any other ideas how to link to Scripto projects from sites?

**Comment by kimisgold** [comment]
I think this is going to be part of a larger conversation on how to integrate Scripto into an Omeka S site. We're planning on having a larger end user-centric discussion along these lines (probably in two sprints when we have more people on hand to contribute).
