### ISSUE TITLE
Broken "Sort" and "Filter" links

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Scripto#24]
On public browse items and browse media pages, clicking on the "Sort" link twice, then clicking on the "Filter" link, opens both menus. The same happens when clicking on the "Filter" link twice, then clicking on the "Sort" link.

**Comment by kimisgold** [comment]
@jimsafley Does https://github.com/omeka-s-modules/Scripto/commit/a6bc7dc02000804b51f0273630210e7e9b7ef083 fix this issue?

**Comment by jimsafley** [comment]
It fixes the issue, though another one appeared. Continuously click on the links, alternating between them. You should notice a slowdown until the page hangs. Looks like a memory leak.

**Comment by kimisgold** [comment]
Ah yeah. I'll look into it, though admittedly this is pushing against the edges of my JS/jQuery knowledge—I may need another set of eyes on it.
