### ISSUE TITLE
Full Release

### ISSUE THREAD

**Issue by DanielBrett** [omeka-s-modules/Scripto#32]
Hey guys!

I know you are swamped with tons of projects at the moment so no rush on a reply.  I was wondering if you had a tentative date for a completed version of the module.  I work for Brock University and we have some researchers who would like to use Scripto for their Omeka S sites.

Any feedback would be appreciated!

Thank you!

Daniel Brett
Brock University
Digital Scholarship Lab Technical Support

**Comment by jimsafley** [comment]
We should release the beta version by April 2019.
