### ISSUE TITLE
Watchlist feature needs orientation.

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/Scripto#36]
Testers had trouble understanding the watchlist feature. How do we explain it to our users, especially to those with little Mediawiki experience? (Can we assume that the majority of Scripto users will have Mediawiki experience?)

**Comment by mebrett** [comment]
Using the existing PWD transcriber base as an example, I don't think we can assume they have mediawiki experience. 

We could probably add some text to the watchlist page explaining how it works - "use this page/feature to track the transcription and approval status of an individual media item" (and then we might want to put in the documentation how to change "media item" to something else for single projects).

I'm not sure how to make "watch media" on the [individual media pages](http://dev.wardepartmentpapers.org/scripto/1/79268/141914) clearer - maybe "track this media"?

**Comment by jdauteri** [comment]
I agree with Megan--"track this media" would be clearer. Could we change "watchlist" to "tracked media" or something like that?

**Comment by kimisgold** [comment]
We now have custom project vocabulary that could make this specific phrasing trickier. "Media" could be labeled differently across projects: "page", "image", etc. Would "track this media" be confusing within a project that calls its media "pages"?

**Comment by jdauteri** [comment]
That's a good point. It does have the potential to be confusing. Although, maybe "media" is general enough that people would assume it is a kind of catch-all, especially if they see "Track this media" repeated across different media types.
