### ISSUE TITLE
"Projects" view creates extra layer for single project instances.

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/Scripto#38]
There is a use case where users will only collaborate on a single project in this version of Scripto. They may want to take advantage of the linked data capabilities of Omeka S while using Scripto for their single project or want other features not present in Omeka Classic's Scripto. (Papers of the War Department, our test case, is one instance even.)

In this use case, the projects view is an unnecessary layer users must click through in their workflow. We should consider solutions that would enable a single project Scripto instance to skip straight to the documents/items view. I seem to recall concern from @jimsafley regarding the difficulty in manipulating the routes, alongside other reasons for leaving the projects view as is, but it might be good to keep a record of the discussion here.

**Comment by jimsafley** [comment]
If I understand you correctly this is already resolved. Users can enter a Scripto project that's contextualized for a site, which removes the "Projects" link and adds a link back to the site. Site admins can create a link to a site-specific project by adding a "Scripto" block to a page.
