### ISSUE TITLE
Provide custom interface label options for project contexts

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/Scripto#39]
Right now the interface is relying heavily on Mediawiki's default wording for interface labels, which creates confusion for Scripto's core users navigating its views. Testers had trouble finding where to transcribe or translate. Would it be possible to enable custom interface labels in a project's options to provide better context for the user? I envision it as a form where re-nameable terms could be customized via text fields. Some suggestions for custom options:

- Edit (Ex: "Transcribe", "Translate")
- Item (Ex: "Document", "Book")
- Media (Ex: "Page", "Image")

**Comment by jimsafley** [comment]
This will be more of an undertaking than I thought. An administrator cannot simply set a custom label for "Item," "Media," and "Edit" because these labels exist as parts of unique strings that must be individually translated and pluralized throughout the public and admin interfaces. The best solution, I think, is to provide a list of predefined alternatives to "Item," "Media," and "Edit" (like those shown above) and map them to the translatable strings during runtime.

**Comment by jimsafley** [comment]
WIP in `custom-types` branch

**Comment by jimsafley** [comment]
@mebrett @kimisgold For the purpose of enabling custom interface labels I've added three new settings that can be used to define the nature of the project: item type, media type, and content type. A project administrator can select from a list of types that we provide. So far the lists include the following:
- Item type:
    - Generic item
    - Document
    - Manuscript
    - Audio
    - Video
- Media type:
    - Generic media
    - Page
    - Image
- Content type
    - Generic content
    - Transcription
    - Translation
    - Description
What are your thoughts on these lists? Can you think of any additions? Bear in mind that these settings are only used to clarify the interface and do not have any effect on behavior.

**Comment by jimsafley** [comment]
For example, I could (and probably should) add "Paper" to the item types, and "Folio," "Sheet," "Leaf," and "Segment" to the media types.

**Comment by kimisgold** [comment]
Some ideas:

* Item type
  * Book
  * Journal
* Media type
  * Entry

Also, the "content type" term could replace "Text" in the toggle navigation ("Text | Discussion") on the media/show view.
