### ISSUE TITLE
Include filters for search

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/Scripto#41]
Right now, Scripto includes a simple search that looks through content throughout the whole installation. There is a use case for wanting to filter the search to a single project, or even using filters like by media type or status.

**Comment by jimsafley** [comment]
The simple search should only query the current project.

**Comment by kimisgold** [comment]
Aah, this affects #40 as well then. Still, I think some kind of eventual advanced search or results filters would be welcome features.

**Comment by kimisgold** [comment]
I forgot that filters do exist and can be performed upon search results.
