### ISSUE TITLE
How do we introduce new users to Scripto's workflow?

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/Scripto#43]
Scripto is shaping up to be a robust tool that may require some guidance for first time users. A tester wanted some kind of workflow orientation, so we should think about how to assist newcomers. My first thought is a some copy that links to "Getting Started" documentation, but I'm unsure where that would go. 

The success message upon creating an account still requires the user to verify their account. Verifying the account sends the user to a mediawiki page. Is there a way to detect the user's first time visiting the dashboard? We could also keep a message linking to a "Getting Started" guide on the dashboard with an option to turn it off.

**Comment by mebrett** [comment]
Is this something we could model in the Project Guidelines section of a Scripto project? I believe we originally thought of that section as the "how to transcribe/translate" section, but it might also work for this?

(We could provide sample text in the documentation)

**Comment by jdauteri** [comment]
Yes, using the Project Guidelines section was my thought also; especially if we direct users to the browse page instead of the dashboard (as Kim suggested in issue #48 ).
