### ISSUE TITLE
Should we include the document name higher in the media name heading?

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/Scripto#44]
In my experience with Scripto and Omeka projects, users often gloss over nicely naming media, resulting in a lot of garbled strings as media titles. Testers found these titles unhelpful, and though we can't control what people name their media, maybe we should bump the associated document's name from the media subheading to its primary heading.

**Comment by jdauteri** [comment]
I think it would be helpful to switch the headers. I see on the dashboard that it names the document you worked on then lists media #1 if you worked on the first page, media #2 for the second page, etc. Would it be possible to incorporate that kind of naming into the media-level view?
<img width="708" alt="screen shot 2019-02-11 at 2 10 28 pm" src="https://user-images.githubusercontent.com/25283961/52587011-f1a03280-2e06-11e9-9e5d-42b57e11328e.png">
