### ISSUE TITLE
Empty media metadata column becomes dead space.

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/Scripto#45]
There seem to be two types of Omeka projects in the world: those who care about media metadata and those that don't. The latter is a common scenario, and in these use cases, the media metadata column is a lot of wasted space. Maybe we can find some way to rearrange space if media metadata is empty.

**Comment by kimisgold** [comment]
This was a tester suggestion: 

> Metadata sidebar appears without any metadata so maybe remove this or import document-level information—that could be helpful during the transcription process to check names/places that are unclear in the document.

**Comment by jdauteri** [comment]
I think that was my suggestion from testing. Looking at it again, I realize that the metadata field disappears when you switch to transcribe view (where I envisioned document-level metadata to be useful), so perhaps the better option is to just remove it if empty? If people want to have the document-level metadata available for transcription help, they can just open each media file in its own tab and toggle back and forth.
