### ISSUE TITLE
Sort/Filter Options

### ISSUE THREAD

**Issue by jdauteri** [omeka-s-modules/Scripto#54]
When changing sort/filter options it does not jump back to the first page of results (so if I re-sort from page 12 it keeps me on that page), which could be confusing for some users. Also if there are no filtered results on the page that you sort/filter from if will say “No Scripto documents found” (screenshot below)-- for example, I filtered for “In Progress” items from page 12 but there are not enough results to fill twelve pages so it said no documents found. If I manually toggle back to page one the six documents with this status are displayed.
![screen shot 2019-03-04 at 1 36 33 pm](https://user-images.githubusercontent.com/25283961/53755810-74a42e00-3e85-11e9-94fe-cd0bd645e209.png)

**Comment by jimsafley** [comment]
You're right, the current page shouldn't carry over to the next page when filtering. It's [fixed](https://github.com/omeka/omeka-s/commit/d8f3f22b98ae0089d9b5260408c41096c8be7f86) in the next version of Omeka S. I'm hesitant to reset the page when sorting, however. It's typical behavior for the current page to carry over when sorting.

**Comment by jdauteri** [comment]
Yes, that makes sense for sorting. Since the filter is fixed, should I go ahead and close this issue?
