### ISSUE TITLE
Misleading placeholder texts for public search

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Scripto#59]
The placeholder text used for the public search inputs are misleading. Currently the item browse page and media browse page both say "Search <project name>". More accurately they should say something like "Search project items" and "Search item media", respectively.

Also, there is concern that placeholder text isn’t as accessible as a label/hint, so perhaps input labels would be better.

**Comment by kimisgold** [comment]
The inputs already have `aria-label` attributes that use the same value as the search placeholder, which has been our standard pattern for text input accessibility. Are you talking about something different?

**Comment by jimsafley** [comment]
No, just an oversight.

**Comment by mebrett** [comment]
I think with the aria label it should be good in terms of accessibly.

I do wonder if it makes sense to add an external label for people who click into the field without looking (open to discussion on this)
