### ISSUE TITLE
Project list browse smushed to the left

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/Scripto#67]
When browsing items in a list, the table doesn't run the width of the page. On a smaller screen (like my laptop) or at smaller browser widths, the Status and % complete columns get very smushed. 

![Screen Shot 2020-01-10 at 11 29 13 AM](https://user-images.githubusercontent.com/2314070/72169094-73dd0200-339c-11ea-9bea-50901525da77.png)

**Comment by kimisgold** [comment]
@mebrett The fix should be ready for testing.

* Project description width should cap out at around 800px for readability.
* Item table should always be full width of the page.

**Comment by mebrett** [comment]
Looks much better! Is there any way of giving the column for % a little more room in the list view?

<img width="1264" alt="Screen Shot 2020-01-13 at 2 23 11 PM" src="https://user-images.githubusercontent.com/2314070/72285029-50ba8880-3610-11ea-8500-5c3f88dba969.png">
