### ISSUE TITLE
Styling options for Scripto project page block?

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/Scripto#68]
In its present form, the Scripto block for S sites just creates a basic link - nothing remarkable about it ([example here](scriptosite/page/project)). Since it is a block and stands on its own, could we either give it some oomph (make it a header?) or give it some styling options (alignment? bold/not bold)?

**Comment by jimsafley** [comment]
What's there currently is just placeholder content. I agree it could use some oomph. @kim We should discuss this at some point.
