### ISSUE TITLE
Add filter by recent notes?

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/Scripto#71]
Would it be possible to add a filter to the admin side, along with "is new" "is not approved" etc, which would look for recently edited notes? They're not used often in our project, and are therefore easy to miss.

**Comment by jimsafley** [comment]
It is possible, though tricky. Scripto does not save the timestamp of a notes page (it's saved in MediaWiki) so we'd have to find a way to do that; and we'd have to determine what "recently edited" means to a filter. I suppose we could have several filters:

- Has notes
- Has notes (past day)
- Has notes (past week)
- Has notes (past month)
- Has notes (past year)

Or we could simply add a sort by "Last edited (notes)" option.

**Comment by mebrett** [comment]
What I was looking for would be met by "Last edited (notes)", which also helpfully includes anything which *has* notes.
