### ISSUE TITLE
Testing: configurable media types

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Scripto#74]
The **master** branch has a new feature that lets project owners configure which media types to include in the project. When editing a project you should see a "Media types" multiple select. Select one media type, save the form, and sync the project. The Scripto items should _only_ contain media with the selected type. Do the same for other combinations of media types (don't forget to sync). If you select no media types, all media should be included.

**Comment by mebrett** [comment]
All items in the set show up, even if they don't have the right kind of media - those without any "acceptable" media just get a Media Count of 0 and are automatically approved. 
However, it only seems to apply to uploaded media. I have one item in the set with a YouTube media, and one with HTML, and both of those came through even though the media type was set to `image/jpeg`
Can send you the link if interested

**Comment by jimsafley** [comment]
Thanks for noticing that. It is odd. I've [asked the original developer](https://github.com/omeka-s-modules/Scripto/pull/69/files#r433492607) about this behavior. We'll see what he thinks about it.

**Comment by mebrett** [comment]
Other than the issue with non-uploaded media, it works as expected. If I edit the project to change the media type, then sync, it removes all the previously synced media. 

Worth noting: transcriptions/translations which were in progress/completed/approved get reset to New when the media type is removed and then re-added, but the content is still there (what gets pulled in from MediaWiki)

**Comment by mebrett** [comment]
Ex. Reel3_0024 http://dev.omeka.org/omeka-s/scripto/10/item

**Comment by jimsafley** [comment]
> transcriptions/translations which were in progress/completed/approved get reset to New when the media type is removed and then re-added

This is expected. When you remove a media type and sync, you're deleting all existing Scripto media with that media type, but you're not deleting the corresponding MediaWiki page. When you re-add the media type and sync, you're re-creating those Scripto media with default metadata (e.g. a "New" status) and they retain their MediaWiki content. I consider this to be a beneficial side-effect.

**Comment by jimsafley** [comment]
I made changes to the master branch that should address the unusual behavior you saw regarding media without media types being synced. Now you should have an option to select "[No media type]" in addition to the other media types. This does require re-testing, since I changed the way syncing works.

**Comment by mebrett** [comment]
If I select a media type, then attachments from HTML input or a YouTube don't get counted as media.

If I select "no media type," the only items with media count are those with non-upload/import media types (again, YouTube, HTML, etc). Is this expected behavior?

**Comment by jimsafley** [comment]
Yes, that's expected. Would it be clearer if the option was "[Media without media type]" instead of "[No media type]"?

**Comment by mebrett** [comment]
I think it would. And I can explain it in the documentation.

**Comment by mebrett** [comment]
I like the change in wording. Give me a chance to update screenshots and add a line in the documentation and we should be good to go
