### ISSUE TITLE
Default sorting on public browse page

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Scripto#75]
This [forum post](https://forum.omeka.org/t/how-to-set-the-default-filter-option-on-a-scripto-project/11685) makes me wonder if the public browse page should sort by "Last edited" (ascending) by default. This will make all new items (and items without media) jump to the top of the page, pushing down all others, including items that are in progress, approved, and not approved. Should this be the default behavior?

**Comment by mebrett** [comment]
I'm not completely sold on the idea, for a few reasons:
- Approved items can already be filtered out of what's showing up.
- There is something to be said for having in-progress items show up pretty early on.
  - For one, it shows people that there is activity on the project, that other people are engaged. If we pushed in-progress down, no one would *ever* see them with the volume of documents in PWD. 
  - For another, sometimes users abandon an item halfway through, and there are people who like to find those and finish them. 

I do think we could/should add the information on how to change the sort order to the documentation. I know getting into the code of a module is more complicated than we usually get, but this is the kind of setting people like to adjust based on the kind of project. 

Another option would be to make the sort and filter options on the public side pop more (or explain how to do this). At the moment they're subtle.  I went to see what the Smithsonian Transcription site does, and they don't filter out complete by default - but they do make it easy for the public side user to do so. https://transcription.si.edu/project/27726?status=transcription

**Comment by jimsafley** [comment]
Good points. I agree. I like the idea of showing the filters more prominently, along the lines of your example. Something like:

> Show items that need [transcription] | [all]

**Comment by kimisgold** [comment]
Reading Megan's use case notes, I agree that we should probably break out at least the filters out of their drop down on the public side. The single click access seems potentially worth adding the extra vertical space in the browse header. My only concern would be if we wanted more than the two filters Jim mentions, that header could get overly tall, especially with some translated strings. The compromise would be leaving them as select elements but removing the extra click to expose them.

Tangentially, what is the current default sorting on public browse? I went to PWD to check as a reference point, and the sorting only shows "Last transcribed (Descending)" as selected by default, but the listing doesn't seem to match up.

**Comment by kimisgold** [comment]
That works for me. I'm going to experiment with the exact placement, because even with that many items, I can see it needing its own line in some translations.
