### ISSUE TITLE
Zoom and rotate not working after upgrade

### ISSUE THREAD

**Issue by dmbmwl** [omeka-s-modules/Scripto#76]
We host Scripto/OmekaS on Reclaim hosting.  Reclaim upgraded OmekaS automatically. When we applied the required/current Scripto update, the zoom and rotate functionality on items stopped working.  I've traced it as best I can, and believe its coming from an error in the panzoom js. I'm seeing:

> [Warning] jQuery.Deferred exception: undefined is not an object (evaluating 'b.cssProps.transform.replace') (2) (jquery.min.js, line 2)
> g — jquery.panzoom.min.js:2:1188
> (anonymous function) — jquery.panzoom.min.js:2:12637
> each — jquery.min.js:2:2981
> applyPanzoom — scripto.js:13
> (anonymous function) — media.js:29
> e — jquery.min.js:2:30011
> (anonymous function) — jquery.min.js:2:30309
> undefined
> 
> [Error] TypeError: undefined is not an object (evaluating 'b.cssProps.transform.replace')
> 	(anonymous function) (jquery.min.js:2:31678)

I appreciate any insights.

**Comment by jimsafley** [comment]
I apologize for the late response. Thank you for bringing this to our attention. We are [working to fix the issue](https://github.com/omeka-s-modules/Scripto/compare/update-media-viewer) in the next release.
