### ISSUE TITLE
Deprecated error with public function jsonSerialize() when editing a scripto project

### ISSUE THREAD

**Issue by GitByrd** [omeka-s-modules/Scripto#84]
The following error occurred after hitting the "edit project" in the actions dropdown options of the Scripto admin section. (testing on Omeka 4.0.3, with MediaWiki 1.39.3)

`Deprecated: Return type of Scripto\Api\Representation\ScriptoReviewerRepresentation::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/schaffer/dev.schafferlibrarycollections.org/modules/Scripto/src/Api/Representation/ScriptoReviewerRepresentation.php on line 21`

I am still able to make and save edits in the project.

**Comment by jimsafley** [comment]
Thanks for reporting the error. The fix will be in the next release.
