### ISSUE TITLE
Scripto vocabulary

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Scripto#9]
This module will come with a vocabulary of properties that describe Scripto media content. They'll include:

- **content**: A plain text representation of the content of a resource;
- **transcription**: A transcription of a resource (sub-property of **content**);
- **translation**: A translation of a resource (sub-property of **content**).

@sheilabrennan, @mebrett , @alyssafahringer I wonder if you can think of more ways people will use Scripto other than for transcribing or translating.

**Comment by sheilabrennan** [comment]
I think you may have gotten all of the possibilities, Jim.

**Comment by mebrett** [comment]
That works - "content" can be as much a description of the item (if there's a sketch on the page) as it can the transcription/translation
